export const GOOGLE_SIGNIN = 'AUTH/GOOGLE_SIGNIN',
  EMAIL_REGISTER = 'AUTH/EMAIL_REGISTER',
  EMAIL_SIGNIN = 'AUTH/EMAIL_SIGNIN',
  REGISTER_AUTH_UID = 'AUTH/REGISTER_AUTH_UID',
  SIGNIN_AUTH_UID = 'AUTH/SIGNIN_AUTH_UID',
  SIGN_OUT = 'AUTH/SIGN_OUT';
